The notebook contain at least two questions about each of these topics:

* Creating Numpy array
* Basic operations on Numpy arrays
* NumPy array statistical functions
* Converting Numpy array to dataframe pandas

In [ ]:
!pip install numpy

**NumPy: It provides a powerful array object (numpy.ndarray) that is efficient for numerical operations. If you need to perform element-wise operations or linear algebra computations, NumPy is often more suitable.**

In [1]:
#import the library
import numpy as np

In [4]:
# Question 1: Creating Numpy array
# Create a 2D Numpy array with shape (3, 3) filled with zeros.
shape = (3,3)
d3_array = np.zeros(shape)
print(d3_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# Question 2: Creating Numpy array
# Create a 2D Numpy array with shape (2, 3) filled with ones.
shape = (2,3)
d2_array = np.ones(shape)
print(d2_array)


[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
# Question 3: Creating Numpy array
# How can you create a 1D Numpy array of oddly numbers from 1 to 20 using linspace

arr = np.linspace(start=1,stop=20, num=10, dtype=int)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 20])

In [21]:
# Question 4: Basic operation on Numpy
# Given two Numpy arrays salaries = [677, 818.2, 234] and overtime = [45, 65, 96], perform element-wise addition to add salaries and overtime.
salaries = np.array([677, 818.2, 234])
overtime = np.array([45, 65, 96])

sum_salaries = salaries.sum()
sum_overtime = overtime.sum()
print(sum_salaries, sum_overtime)


weird_addition = salaries + overtime
print(weird_addition)

1729.2 206
[722.  883.2 330. ]


In [23]:
# Question 5: using the array in Question 4, Perform element-wise exponentiation of salries power overtime
weird_exponential = salaries ** overtime
print(weird_exponential)


[2.37952401e+127 2.16703480e+189 2.78434029e+227]


In [29]:
# Question 6: NumPy array statistical functions
# Create a 10 x 4 NumPy array with random values
data = np.random.rand(10, 4)

print("10 x 4 NumPy array with random values:")
print(data)


# calculate the total mean and standard deviation of the table
print(data.mean(), np.mean(data))
print(data.std(), np.std(data))


10 x 4 NumPy array with random values:
[[0.32016064 0.07449832 0.87142475 0.86976361]
 [0.67081075 0.50342138 0.33276581 0.68139675]
 [0.30296597 0.90620229 0.30643023 0.54544993]
 [0.29954047 0.72871795 0.657485   0.14165371]
 [0.38297007 0.22423213 0.23340797 0.00187059]
 [0.32963132 0.65201753 0.35320324 0.34364173]
 [0.67401323 0.58901581 0.5965434  0.2128295 ]
 [0.24552654 0.82150254 0.50116151 0.68948418]
 [0.85428955 0.91452856 0.98324551 0.66096566]
 [0.26750251 0.94044371 0.4897342  0.81790828]]
0.5248089203579323 0.5248089203579323
0.2640875621084595 0.2640875621084595


In [30]:
# Calculate the mean and standard deviation for each column
mean_values = np.mean(data, axis=0)
std_deviations = np.std(data, axis=0)

print("\nMean values for each column:")
print(mean_values)

print("\nStandard deviations for each column:")
print(std_deviations)


Mean values for each column:
[0.4347411  0.63545802 0.53254016 0.49649639]

Standard deviations for each column:
[0.20378241 0.28127502 0.23519778 0.2859917 ]


# Reading data from libraries


https://scikit-learn.org/stable/datasets/toy_dataset.html

Scikit-learn is a widely-used Python library for machine learning and statistical modeling.

In [31]:
!pip install scikit-learn

^C
ERROR: Operation cancelled by user

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip


In [33]:
from sklearn.datasets import load_diabetes

# Load the diabetes dataset
diabetes = load_diabetes()
# Access the feature matrix (data)
data = diabetes.data
print(data.shape)
print(type(data))

(442, 10)
<class 'numpy.ndarray'>


In [34]:
# Display the top three rows of the feature matrix
print("Top three rows of the feature matrix:")
print(data[:3])

Top three rows of the feature matrix:
[[ 0.03807591  0.05068012  0.06169621  0.02187239 -0.0442235  -0.03482076
  -0.04340085 -0.00259226  0.01990749 -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 -0.02632753 -0.00844872 -0.01916334
   0.07441156 -0.03949338 -0.06833155 -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 -0.00567042 -0.04559945 -0.03419447
  -0.03235593 -0.00259226  0.00286131 -0.02593034]]


In [36]:
#Question 7
## Calculate the statistic paramters of the columns/variables

means = data.mean()
std_devs = data.std()
mins = data.min()
maxs = data.max()

# Print the calculated statistical parameters
print("Statistical parameters for each column:")
print("Mean:", means)
print("Standard Deviation:", std_devs)
print("Minimum:", mins)
print("Maximum:", maxs)

Statistical parameters for each column:
Mean: -1.42671194114726e-17
Standard Deviation: 0.04756514941544941
Minimum: -0.13776722569000302
Maximum: 0.19878798965729408


In [37]:
#Question 8:
#Calculate the correlation between variables
# rowvar=False means that each column represents a variable,
correlation_matrix = np.corrcoef(data, rowvar=False)

# Print the correlation matrix
print(correlation_matrix)


[[ 1.          0.1737371   0.18508467  0.33542759  0.26006082  0.21924314
  -0.07518097  0.2038409   0.27077424  0.30173101]
 [ 0.1737371   1.          0.0881614   0.24101049  0.03527682  0.14263726
  -0.37908963  0.33211509  0.14991614  0.20813322]
 [ 0.18508467  0.0881614   1.          0.3954109   0.24977742  0.26116991
  -0.36681098  0.4138066   0.44615654  0.38867999]
 [ 0.33542759  0.24101049  0.3954109   1.          0.24246402  0.18554846
  -0.17876163  0.25765005  0.39348011  0.39043002]
 [ 0.26006082  0.03527682  0.24977742  0.24246402  1.          0.89666296
   0.05151936  0.54220728  0.51550292  0.32571675]
 [ 0.21924314  0.14263726  0.26116991  0.18554846  0.89666296  1.
  -0.19645512  0.65981689  0.31835667  0.29060038]
 [-0.07518097 -0.37908963 -0.36681098 -0.17876163  0.05151936 -0.19645512
   1.         -0.73849273 -0.39857729 -0.2736973 ]
 [ 0.2038409   0.33211509  0.4138066   0.25765005  0.54220728  0.65981689
  -0.73849273  1.          0.61785897  0.41721211]
 [ 0.270

In [39]:
#Question 9 Calculate the minimum and maximum values in the correlation matrix
min_value = np.min(correlation_matrix)
max_value = np.max(correlation_matrix)

# Print the minimum and maximum values
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: -0.7384927292583834
Maximum value: 1.0


In [41]:
#Question 10: Convert Numpy array to DataFrame
import pandas as pd
import numpy as np

df = pd.DataFrame(data)
df



/var/folders/ck/vgxn_9f907d122j56f3203gm0000gn/T/ipykernel_60807/4227126886.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


0         1         2         3         4         5         6  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

            7         8         9  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

**Descriptive statistics using Pandas DataFrame are much more efficient and easier compared to NumPy arrays.**

In [42]:
df.describe()

0             1             2             3             4  \
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02   
mean  -2.511817e-19  1.230790e-17 -2.245564e-16 -4.797570e-17 -1.381499e-17   
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02   
min   -1.072256e-01 -4.464164e-02 -9.027530e-02 -1.123988e-01 -1.267807e-01   
25%   -3.729927e-02 -4.464164e-02 -3.422907e-02 -3.665608e-02 -3.424784e-02   
50%    5.383060e-03 -4.464164e-02 -7.283766e-03 -5.670422e-03 -4.320866e-03   
75%    3.807591e-02  5.068012e-02  3.124802e-02  3.564379e-02  2.835801e-02   
max    1.107267e-01  5.068012e-02  1.705552e-01  1.320436e-01  1.539137e-01   

                  5             6             7             8             9  
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  
mean   3.918434e-17 -5.777179e-18 -9.042540e-18  9.293722e-17  1.130318e-17  
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  
min   -1.156131e-01 -1.023071e-01 -7.639450e-02 -1.260971e-01 -1.377672e-01  
25%   -3.035840e-02 -3.511716e-02 -3.949338e-02 -3.324559e-02 -3.317903e-02  
50%   -3.819065e-03 -6.584468e-03 -2.592262e-03 -1.947171e-03 -1.077698e-03  
75%    2.984439e-02  2.931150e-02  3.430886e-02  3.243232e-02  2.791705e-02  
max    1.987880e-01  1.811791e-01  1.852344e-01  1.335973e-01  1.356118e-01