The notebook contain at least two questions about each of these topics:

* Creating Numpy array
* Basic operations on Numpy arrays
* NumPy array statistical functions
* Reading csv using Numpy
* Converting Numpy array to dataframe pandas

In [1]:
!pip install numpy

**NumPy: It provides a powerful array object (numpy.ndarray) that is efficient for numerical operations. If you need to perform element-wise operations or linear algebra computations, NumPy is often more suitable.**

In [2]:
#import the library
import numpy as np

In [20]:
# Question 1: Creating Numpy array
# Create a 2D Numpy array with shape (3, 3) filled with zeros.

zeros_array = np.zeros((3, 3))
print("2D NumPy array with shape (3, 3) filled with zeros:")
print(zeros_array)

2D NumPy array with shape (3, 3) filled with zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Question 2: Creating Numpy array
# Create a 2D Numpy array with shape (2, 3) filled with ones.

zeros_array = np.ones((2, 3))
print("2D NumPy array filled with zeros:")
print(zeros_array)

2D NumPy array filled with zeros:
[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
# Question 3: Creating Numpy array
# How can you create a 1D Numpy array of oddly numbers from 1 to 20 using linspace
odd_numbers = np.linspace(1, 20, 10, dtype=int)

print("1D NumPy array of odd numbers from 1 to 20:")
print(odd_numbers)

1D NumPy array of odd numbers from 1 to 20:
[ 1  3  5  7  9 11 13 15 17 20]


In [8]:
# Question 4: Basic operation on Numpy
# Given two Numpy arrays salaries = [677, 818.2, 234] and overtime = [45, 65, 96], perform element-wise addition to add salaries and overtime.
salaries = np.array([677, 818.2, 234])
overtime = np.array([45, 65, 96])
result_addition = salaries + overtime
result_addition


array([722. , 883.2, 330. ])

In [9]:
# Question 5: using the array in Question 4, Perform element-wise exponentiation of salries power overtime
result_exp = np.power(salaries,overtime)
print(result_exp)


[2.37952401e+127 2.16703480e+189 2.78434029e+227]


In [11]:
# Question 6: NumPy array statistical functions
# Create a 10 x 4 NumPy array with random values
data = np.random.rand(10, 4)

print("10 x 4 NumPy array with random values:")
print(data)


# calculate the total mean and standard deviation of the table
mean_value = np.mean(data)
std_deviation = np.std(data)
mean_value, std_deviation


10 x 4 NumPy array with random values:
[[0.31630951 0.7520752  0.90959113 0.94158986]
 [0.3543122  0.5232186  0.82742391 0.96079316]
 [0.7649468  0.57423746 0.04605592 0.26022494]
 [0.7962793  0.8300666  0.12144513 0.74567444]
 [0.48554472 0.43650363 0.81873939 0.31554642]
 [0.5526494  0.48325676 0.37864855 0.27684349]
 [0.08042099 0.02408804 0.95036487 0.24982897]
 [0.30798587 0.92741749 0.46093933 0.00279651]
 [0.2885451  0.81796736 0.54009558 0.3127837 ]
 [0.97562127 0.98416926 0.43174197 0.71380129]]


(0.5385136032846829, 0.2965986553056721)

In [12]:
# Calculate the mean and standard deviation for each column
mean_values = np.mean(data, axis=0)
std_deviations = np.std(data, axis=0)

print("\nMean values for each column:")
print(mean_values)

print("\nStandard deviations for each column:")
print(std_deviations)


Mean values for each column:
[0.49226152 0.63530004 0.54850458 0.47798828]

Standard deviations for each column:
[0.26441864 0.27285313 0.30459078 0.31539095]


# Reading data using Numpy


https://scikit-learn.org/stable/datasets/toy_dataset.html

Scikit-learn is a widely-used Python library for machine learning and statistical modeling.

In [16]:
!pip install scikit-learn

In [21]:
from sklearn.datasets import load_diabetes

# Load the diabetes dataset
diabetes = load_diabetes()
# Access the feature matrix (data)
data = diabetes.data
print(data.shape)
print(type(data))

(442, 10)
<class 'numpy.ndarray'>


In [22]:
# Display the top three rows of the feature matrix
print("Top three rows of the feature matrix:")
print(data[:3])

Top three rows of the feature matrix:
[[ 0.03807591  0.05068012  0.06169621  0.02187239 -0.0442235  -0.03482076
  -0.04340085 -0.00259226  0.01990749 -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 -0.02632753 -0.00844872 -0.01916334
   0.07441156 -0.03949338 -0.06833155 -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 -0.00567042 -0.04559945 -0.03419447
  -0.03235593 -0.00259226  0.00286131 -0.02593034]]


In [23]:
#Question 7
## Calculate the statistic paramters of the columns/variables

means = np.mean(data, axis=0)  # Mean of each column
std_devs = np.std(data, axis=0)  # Standard deviation of each column
mins = np.min(data, axis=0)  # Minimum value of each column
maxs = np.max(data, axis=0)  # Maximum value of each column

# Print the calculated statistical parameters
print("Statistical parameters for each column:")
print("Mean:", means)
print("Standard Deviation:", std_devs)
print("Minimum:", mins)
print("Maximum:", maxs)

Statistical parameters for each column:
Mean: [-1.44429466e-18  2.54321451e-18 -2.25592546e-16 -4.85408596e-17
 -1.42859580e-17  3.89881064e-17 -6.02836031e-18 -1.78809958e-17
  9.24348582e-17  1.35176953e-17]
Standard Deviation: [0.04756515 0.04756515 0.04756515 0.04756515 0.04756515 0.04756515
 0.04756515 0.04756515 0.04756515 0.04756515]
Minimum: [-0.10722563 -0.04464164 -0.0902753  -0.1123988  -0.12678067 -0.11561307
 -0.10230705 -0.0763945  -0.12609712 -0.13776723]
Maximum: [0.11072668 0.05068012 0.17055523 0.13204362 0.15391371 0.19878799
 0.18117906 0.18523444 0.13359728 0.13561183]


In [24]:
#Question 8:
#Calculate the correlation between variables
# rowvar=False means that each column represents a variable,
correlation_matrix = np.corrcoef(data, rowvar=False)

# Print the correlation matrix
print("Correlation matrix between variables:")
print(correlation_matrix)

Correlation matrix between variables:
[[ 1.          0.1737371   0.18508467  0.33542759  0.26006082  0.21924314
  -0.07518097  0.2038409   0.27077424  0.30173101]
 [ 0.1737371   1.          0.0881614   0.24101049  0.03527682  0.14263726
  -0.37908963  0.33211509  0.14991614  0.20813322]
 [ 0.18508467  0.0881614   1.          0.3954109   0.24977742  0.26116991
  -0.36681098  0.4138066   0.44615654  0.38867999]
 [ 0.33542759  0.24101049  0.3954109   1.          0.24246402  0.18554846
  -0.17876163  0.25765005  0.39348011  0.39043002]
 [ 0.26006082  0.03527682  0.24977742  0.24246402  1.          0.89666296
   0.05151936  0.54220728  0.51550292  0.32571675]
 [ 0.21924314  0.14263726  0.26116991  0.18554846  0.89666296  1.
  -0.19645512  0.65981689  0.31835667  0.29060038]
 [-0.07518097 -0.37908963 -0.36681098 -0.17876163  0.05151936 -0.19645512
   1.         -0.73849273 -0.39857729 -0.2736973 ]
 [ 0.2038409   0.33211509  0.4138066   0.25765005  0.54220728  0.65981689
  -0.73849273  1.    

In [25]:
#Question 9 Calculate the minimum and maximum values in the correlation matrix
min_value = np.min(correlation_matrix)
max_value = np.max(correlation_matrix)

# Print the minimum and maximum values
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: -0.7384927292583834
Maximum value: 1.0


In [29]:
#Question 10: Convert Numpy array to DataFrame
import pandas as pd
df = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
df.head()


age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930  
3  0.034309  0.022688 -0.009362  
4 -0.002592 -0.031988 -0.046641

**Descriptive statistics using Pandas DataFrame are much more efficient and easier compared to NumPy arrays.**

In [30]:
df.describe()

age           sex           bmi            bp            s1  \
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02   
mean  -2.511817e-19  1.230790e-17 -2.245564e-16 -4.797570e-17 -1.381499e-17   
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02   
min   -1.072256e-01 -4.464164e-02 -9.027530e-02 -1.123988e-01 -1.267807e-01   
25%   -3.729927e-02 -4.464164e-02 -3.422907e-02 -3.665608e-02 -3.424784e-02   
50%    5.383060e-03 -4.464164e-02 -7.283766e-03 -5.670422e-03 -4.320866e-03   
75%    3.807591e-02  5.068012e-02  3.124802e-02  3.564379e-02  2.835801e-02   
max    1.107267e-01  5.068012e-02  1.705552e-01  1.320436e-01  1.539137e-01   

                 s2            s3            s4            s5            s6  
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  
mean   3.918434e-17 -5.777179e-18 -9.042540e-18  9.293722e-17  1.130318e-17  
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  
min   -1.156131e-01 -1.023071e-01 -7.639450e-02 -1.260971e-01 -1.377672e-01  
25%   -3.035840e-02 -3.511716e-02 -3.949338e-02 -3.324559e-02 -3.317903e-02  
50%   -3.819065e-03 -6.584468e-03 -2.592262e-03 -1.947171e-03 -1.077698e-03  
75%    2.984439e-02  2.931150e-02  3.430886e-02  3.243232e-02  2.791705e-02  
max    1.987880e-01  1.811791e-01  1.852344e-01  1.335973e-01  1.356118e-01