The notebook contain at least two questions about each of these topics:

* Creating Numpy array
* Basic operations on Numpy arrays
* NumPy array statistical functions
* Converting Numpy array to dataframe pandas

In [ ]:
!pip install numpy

**NumPy: It provides a powerful array object (numpy.ndarray) that is efficient for numerical operations. If you need to perform element-wise operations or linear algebra computations, NumPy is often more suitable.**

In [ ]:
#import the library
import numpy as np

In [ ]:
# Question 1: Creating Numpy array
# Create a 2D Numpy array with shape (3, 3) filled with zeros.



In [ ]:
# Question 2: Creating Numpy array
# Create a 2D Numpy array with shape (2, 3) filled with ones.


In [ ]:
# Question 3: Creating Numpy array
# How can you create a 1D Numpy array of oddly numbers from 1 to 20 using linspace


1D NumPy array of odd numbers from 1 to 20:
[ 1  3  5  7  9 11 13 15 17 20]


In [ ]:
# Question 4: Basic operation on Numpy
# Given two Numpy arrays salaries = [677, 818.2, 234] and overtime = [45, 65, 96], perform element-wise addition to add salaries and overtime.
salaries = np.array([677, 818.2, 234])
overtime = np.array([45, 65, 96])



array([722. , 883.2, 330. ])

In [ ]:
# Question 5: using the array in Question 4, Perform element-wise exponentiation of salries power overtime



[2.37952401e+127 2.16703480e+189 2.78434029e+227]


In [ ]:
# Question 6: NumPy array statistical functions
# Create a 10 x 4 NumPy array with random values
data = np.random.rand(10, 4)

print("10 x 4 NumPy array with random values:")
print(data)


# calculate the total mean and standard deviation of the table



In [ ]:
# Calculate the mean and standard deviation for each column
mean_values = np.mean(data, axis=0)
std_deviations = np.std(data, axis=0)

print("\nMean values for each column:")
print(mean_values)

print("\nStandard deviations for each column:")
print(std_deviations)

# Reading data from libraries


https://scikit-learn.org/stable/datasets/toy_dataset.html

Scikit-learn is a widely-used Python library for machine learning and statistical modeling.

In [ ]:
!pip install scikit-learn

In [ ]:
from sklearn.datasets import load_diabetes

# Load the diabetes dataset
diabetes = load_diabetes()
# Access the feature matrix (data)
data = diabetes.data
print(data.shape)
print(type(data))

(442, 10)
<class 'numpy.ndarray'>


In [ ]:
# Display the top three rows of the feature matrix
print("Top three rows of the feature matrix:")
print(data[:3])

Top three rows of the feature matrix:
[[ 0.03807591  0.05068012  0.06169621  0.02187239 -0.0442235  -0.03482076
  -0.04340085 -0.00259226  0.01990749 -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 -0.02632753 -0.00844872 -0.01916334
   0.07441156 -0.03949338 -0.06833155 -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 -0.00567042 -0.04559945 -0.03419447
  -0.03235593 -0.00259226  0.00286131 -0.02593034]]


In [ ]:
#Question 7
## Calculate the statistic paramters of the columns/variables



# Print the calculated statistical parameters
print("Statistical parameters for each column:")
print("Mean:", means)
print("Standard Deviation:", std_devs)
print("Minimum:", mins)
print("Maximum:", maxs)

In [ ]:
#Question 8:
#Calculate the correlation between variables
# rowvar=False means that each column represents a variable,
correlation_matrix = np.corrcoef(data, rowvar=False)

# Print the correlation matrix


In [ ]:
#Question 9 Calculate the minimum and maximum values in the correlation matrix


# Print the minimum and maximum values
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: -0.7384927292583834
Maximum value: 1.0


In [ ]:
#Question 10: Convert Numpy array to DataFrame
import pandas as pd



**Descriptive statistics using Pandas DataFrame are much more efficient and easier compared to NumPy arrays.**

In [ ]:
df.describe()